#ifndef __FTD_DRV_FLASH_ACCESS_PDMA_H__
#define __FTD_DRV_FLASH_ACCESS_PDMA_H__

#include <stdint.h>
#include "NuMicro.h"

#define SPI_FLASH_PORT          SPI1
#define SPI_FLASH_MODLUE_CLK    SPI1_MODULE
#define SPI_FLASH_PIN_SET       {PB->SMTEN |= GPIO_SMTEN_SMTEN3_Msk; GPIO_SetSlewCtl(PB, 0xF, GPIO_SLEWCTL_HIGH);}

#define FLASH_SIZE      (0x1000000) //16MB
#define PAGESIZE        (0x100)     //256B
#define ERASE_SIZE_MIN  (0x1000)    //4KB

/**************************************FLASH分区配置开始************************************************ */
#define PARTITION_RESERVED_START_ADDR       (0x0)
#define PARTITION_RESERVED_SIZE             (ERASE_SIZE_MIN)
#define PARTITION_RESERVED_END_ADDR         (0x0 + PARTITION_RESERVED_SIZE)

#define PARTITION_WRITER_MANAGER_START_ADDR (PARTITION_RESERVED_END_ADDR)
#define PARTITION_WRITER_MANAGER_SIZE       (ERASE_SIZE_MIN * 16)
#define PARTITION_WRITER_MANAGER_END_ADDR   (PARTITION_WRITER_MANAGER_START_ADDR + PARTITION_WRITER_MANAGER_SIZE)

#define PARTITION_FW1_INFO_START_ADDR      (PARTITION_WRITER_MANAGER_END_ADDR)
#define PARTITION_FW1_INFO_SIZE            (ERASE_SIZE_MIN * 4)
#define PARTITION_FW1_INFO_END_ADDR        (PARTITION_FW1_INFO_START_ADDR + PARTITION_FW1_INFO_SIZE)

#define PARTITION_FW1_BIN_START_ADDR        (PARTITION_FW1_INFO_END_ADDR)
#define PARTITION_FW1_BIN_SIZE              (ERASE_SIZE_MIN * 384)
#define PARTITION_FW1_BIN_END_ADDR          (PARTITION_FW1_BIN_START_ADDR + PARTITION_FW1_BIN_SIZE)

#define PARTITION_FW1_TRIPLE_START_ADDR    (PARTITION_FW1_BIN_END_ADDR)
#define PARTITION_FW1_TRIPLE_SIZE          (ERASE_SIZE_MIN * 620)
#define PARTITION_FW1_TRIPLE_END_ADDR      (PARTITION_FW1_TRIPLE_START_ADDR + PARTITION_FW1_TRIPLE_SIZE)

#define PARTITION_FW2_INFO_START_ADDR      (PARTITION_FW1_TRIPLE_END_ADDR)
#define PARTITION_FW2_INFO_SIZE            (ERASE_SIZE_MIN * 4)
#define PARTITION_FW2_INFO_END_ADDR        (PARTITION_FW2_INFO_START_ADDR + PARTITION_FW2_INFO_SIZE)

#define PARTITION_FW2_BIN_START_ADDR        (PARTITION_FW2_INFO_END_ADDR)
#define PARTITION_FW2_BIN_SIZE              (ERASE_SIZE_MIN * 384)
#define PARTITION_FW2_BIN_END_ADDR          (PARTITION_FW2_BIN_START_ADDR + PARTITION_FW2_BIN_SIZE)

#define PARTITION_FW2_TRIPLE_START_ADDR    (PARTITION_FW2_BIN_END_ADDR)
#define PARTITION_FW2_TRIPLE_SIZE          (ERASE_SIZE_MIN * 620)
#define PARTITION_FW2_TRIPLE_END_ADDR      (PARTITION_FW2_TRIPLE_START_ADDR + PARTITION_FW2_TRIPLE_SIZE)

#define PARTITION_FW3_INFO_START_ADDR      (PARTITION_FW2_TRIPLE_END_ADDR)
#define PARTITION_FW3_INFO_SIZE            (ERASE_SIZE_MIN * 4)
#define PARTITION_FW3_INFO_END_ADDR        (PARTITION_FW3_INFO_START_ADDR + PARTITION_FW3_INFO_SIZE)

#define PARTITION_FW3_BIN_START_ADDR        (PARTITION_FW3_INFO_END_ADDR)
#define PARTITION_FW3_BIN_SIZE              (ERASE_SIZE_MIN * 384)
#define PARTITION_FW3_BIN_END_ADDR          (PARTITION_FW3_BIN_START_ADDR + PARTITION_FW3_BIN_SIZE)

#define PARTITION_FW3_TRIPLE_START_ADDR    (PARTITION_FW3_BIN_END_ADDR)
#define PARTITION_FW3_TRIPLE_SIZE          (ERASE_SIZE_MIN * 620) 
#define PARTITION_FW3_TRIPLE_END_ADDR      (PARTITION_FW3_TRIPLE_START_ADDR + PARTITION_FW3_TRIPLE_SIZE)

#define PARTITION_CACHE_START_ADDR          (PARTITION_FW3_TRIPLE_END_ADDR)
#define PARTITION_CACHE_SIZE                (ERASE_SIZE_MIN * 1008) 
#define PARTITION_CACHE_END_ADDR            (PARTITION_CACHE_START_ADDR + PARTITION_CACHE_SIZE)
/**************************************FLASH分区配置结束************************************************ */

#if (PARTITION_CACHE_END_ADDR > FLASH_SIZE)
    #error "ERROR: Flash partition configuration exceeds flash size!"
#endif

typedef struct
{
    uint32_t start_addr;
    uint32_t size;
} PARTITION_ADDR_INFO;

typedef enum
{
    PARTITION_RESERVED = 0,
    PARTITION_WRITER_MANAGER,
    PARTITION_FW1_INFO,
    PARTITION_FW1_BIN,
    PARTITION_FW1_TRIPLE,
    PARTITION_FW2_INFO,
    PARTITION_FW2_BIN,
    PARTITION_FW2_TRIPLE,
    PARTITION_FW3_INFO,
    PARTITION_FW3_BIN,
    PARTITION_FW3_TRIPLE,
    PARTITION_CACHE,
    PARTITION_MAX,
} PARTITION_NAME;

// typedef enum
// {
//     FW1_REGION = 0,
//     FW2_REGION,
//     FW3_REGION,
// } FW_REGION;

typedef enum
{
    OPERATION_ERASE = 0,
    OPERATION_WRITE,
    OPERATION_READ,
} PATITION_OPERATION_TYPE;

uint32_t ftd_drv_flash_access_get_partition_start_addr(PARTITION_NAME e_partition);
uint32_t ftd_drv_flash_access_get_partition_size(PARTITION_NAME e_partition);
int8_t ftd_drv_flash_operation (PARTITION_NAME e_partition, PATITION_OPERATION_TYPE ope_type, 
                                    uint32_t addr_offset, uint32_t length, uint8_t *pu8Data);
#endif
