#ifndef __FTD_PROG_EVENT_H__
#define __FTD_PROG_EVENT_H__

typedef enum
{
    FTD_PROG_EVENT_NONE = 0,
    FTD_PROG_EVENT_CHECK_ONLINE,
    FTD_PROG_EVENT_GET_SYSINFO,
    FTD_PROG_EVENT_DEPLOY_SEG_DATA_START,
    FTD_PROG_EVENT_FW_UPDATE_SEG_DATA_START,
    FTD_PROG_EVENT_DEPLOY_SEG_DATA,
    FTD_PROG_EVENT_FW_UPDATE_SEG_DATA,
    FTD_PROG_EVENT_SET_WRITER_INFO,
    FTD_PROG_EVENT_GET_CRC_RESAULT,
    FTD_PROG_EVENT_BURN_START_TEST_TMP, //temp use
    FTD_PROG_EVENT_BURN_START_TMP, //temp use
    FTD_PROG_EVENT_ENTER_IAP_MODE,
} FTD_PROG_EVENT;


#endif 

