#ifndef __FTD_MW_SLAVE_MANAGER_H__
#define __FTD_MW_SLAVE_MANAGER_H__ 

#include "ftd_drv_burn_uart.h"
#include "ftd_mw_hc_manager.h"   // for debug 
#include "ftd_data_model.h"

#include <stdint.h>
#include <stdbool.h>

///////////////////// for deubg

typedef enum
{
    SLAVE_EXT_CMD_ERASE_FLASH = 0x004F,
    SLAVE_EXT_CMD_READ_FLASH  = 0x0050,
    SLAVE_EXT_CMD_PROG_FLASH  = 0x0051,
} EN_SLAVE_EXT_CMD;


#define SLAVE_BOOT_TRIGGER_CNT              (2)
#define SLAVE_BOOT_TRIGGER_DELAY            (80000)//(1000) // 1ms

#define SLAVE_DISABLE_WP_TRIGGER_CNT        (1)

//#define SLAVE_CMD_RETRY_CNT_MAX             (3)


#define SLAVE_FLASH_TEST_ADDR               (0x08021000)
#define SLAVE_FLASH_BIN_ADDR                (0x08008000)
#define SLAVE_FLASH_START_ADDR              SLAVE_FLASH_TEST_ADDR
#define SLAVE_FLASH_PAGE_SIZE               (0x00000100) // 256 bytes per page

// CHIP id 0 : FL100, MAP 0 : memmap version 0
// AUTHOR: authorization info, like rollcode, triple, motor encryption key, etc
// CLIENT: client info
// CONFIG_A, CONFIG_B: configuration data bin partition A and B, generated by automatic compile tool
// FW_BIN_A, FW_BIN_B: fw bin partition A and B
// DEBUG: for wirte debug, could P/E without quit WP operation
#define SLAVE_FLASH_CHIP_0_MAP_0_AUTHOR_ADDR            (0x08002000)
#define SLAVE_FLASH_CHIP_0_MAP_0_CLIENT_ADDR            (0x08003000)
#define SLAVE_FLASH_CHIP_0_MAP_0_CONFIG_A_ADDR          (0x08004000)
#define SLAVE_FLASH_CHIP_0_MAP_0_CONFIG_B_ADDR          (0x08005000)
#define SLAVE_FLASH_CHIP_0_MAP_0_FW_BIN_A_ADDR          (0x08008000)
#define SLAVE_FLASH_CHIP_0_MAP_0_FW_BIN_B_ADDR          (0x08020000)
#define SLAVE_FLASH_CHIP_0_MAP_0_DEBUG_ADDR             (0x08021000)
#define SLAVE_FLASH_CHIP_0_MAP_0_MAX_ADDR               (0x08040000)


#define SLAVE_FLASH_OP_ADDR_SIZE            (4)

/////////////////// SLAVE FLASH STATUS
#define SLAVE_FLASH_STATUS_LEN              (2)
#define SLAVE_FLASH_STATUS_ACK_LEN          (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_STATUS_LEN + CHECKSUM_SIZE)
/////////////////// SLAVE FLASH STATUS END

/////////////////// SLAVE FLASH ERASE
#define SLAVE_FLASH_ERASE_LEN               (4)
#define SLAVE_FLASH_ERASE_ACK_SIZE          (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_ERASE_LEN + CHECKSUM_SIZE)
/////////////////// SLAVE FLASH ERASE END

/////////////////// SLAVE FLASH PROG 
#define SLAVE_FLASH_PROG_SIZE               (SLAVE_FLASH_PAGE_SIZE << 1) // 2 pages, must be multiple of 1page
#define SLAVE_FLASH_OP_LENGTH_SIZE          (3)
#define SLAVE_FLASH_PROG_PRAM_LEN_OFFSET    (FRAME_HEADER_SIZE + CMD_SIZE)
#define SLAVE_FLASH_PROG_EXT_CMD_OFFSET     (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE)
#define SLAVE_FLASH_PROG_ADDR_OFFSET        (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE)
#define SLAVE_FLASH_PROG_LEN_OFFSET         (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE)
#define SLAVE_FLASH_PROG_DATA_OFFSET        (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_OP_LENGTH_SIZE)
#define SLAVE_FLASH_PROG_PRAM_LEN_MAX       (EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_OP_LENGTH_SIZE + SLAVE_FLASH_PROG_SIZE)
#define SLAVE_FLASH_PROG_CMD_SIZE_MAX       (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_OP_LENGTH_SIZE + SLAVE_FLASH_PROG_SIZE + CHECKSUM_SIZE)
#define SLAVE_FLASH_PROG_ACK_LEN            (0x0E)// fixed 14
/////////////////// SLAVE FLASH PROG END

/////////////////// SLAVE FLASH READ 
#define SLAVE_FLASH_READ_SIZE               (SLAVE_FLASH_PAGE_SIZE << 2) // 4 pages, must be multiple of 1page
#define SLAVE_FLASH_READ_LENGTH_SIZE        (4)
#define SLAVE_FLASH_READ_DATA_OFFSET        (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_READ_LENGTH_SIZE)
#define SLAVE_FLASH_READ_CMD_SIZE_MAX       (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_READ_LENGTH_SIZE + CHECKSUM_SIZE)
#define SLAVE_FLASH_READ_CMD_ACK_SIZE_MAX   (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_READ_LENGTH_SIZE + SLAVE_FLASH_READ_SIZE + CHECKSUM_SIZE)
/////////////////// SLAVE FLASH READ END


#define AUTHOR_INFO_CRC_LEN                 (2)



//////////////////////////// debug end
typedef enum
{
    SLAVE_CMD_NONE,                     // 0x00
    SLAVE_CMD_ENTER_BOOT_LOADER,        // 0x01
    SLAVE_CMD_CHECK_CURRENT_VOLTAGE,    // 0x02
    SLAVE_CMD_READ_CHIP_ID,             // 0x03
    SLAVE_CMD_REBOOT_CHIP,              // 0x04
    SLAVE_CMD_SET_CPU_CLK,              // 0x05
    SLAVE_CMD_SET_UART_BAUDRATE,        // 0x06

    SLAVE_CMD_READ_PRODUCTION_TEST_STATUS, // 0x07
    SLAVE_CMD_SET_PROGRAM_JUMP,         // 0x08

    SLAVE_CMD_READ_CODE_CRC,            // 0x09

    SLAVE_CMD_READ_FLASH_ID,            // 0x0A
    SLAVE_CMD_READ_FLASH_STATUS_REG,    // 0x0B
    SLAVE_CMD_SET_FLASH_STATUS_REG,     // 0x0C
    SLAVE_CMD_SET_FLASH_STATUS_QUIT_WP, // 0x0D
    SLAVE_CMD_SET_FLASH_READ_MODE,      // 0x0E
    SLAVE_CMD_SET_FLASH_WRITE_MODE,     // 0x0F
    SLAVE_CMD_SET_FLASH_CLK_DIV,        // 0x10
    SLAVE_CMD_SET_FLASH_SAMPLE_POINT,   // 0x11
    SLAVE_CMD_ERASE_ENTIRE_FLASH,       // 0x12
    SLAVE_CMD_ERASE_FLASH_SECTOR,       // 0x13
    SLAVE_CMD_READ_FLASH_OR_RAM_DATA,   // 0x14
    SLAVE_CMD_WRITE_FLASH_DATA,         // 0x15
    SLAVE_CMD_WRITE_RAM_DATA,           // 0x16
    SLAVE_CMD_RESET_FLASH,              // 0x17
    SLAVE_CMD_SET_FLASH_STATUS_QUIT_WP_PARM, // 0x18
    SLAVE_CMD_ERASE_FLASH_SECTOR_PARM, // 0x19
    SLAVE_CMD_WRITE_FLASH_DATA_PARM,    // 0x1A
    SLAVE_CMD_SET_FLASH_STATUS_REG_PARM, // 0x1B
    SLAVE_CMD_READ_CODE_CRC_PARM,       // 0x1C

    SLAVE_CMD_STATE_SORT,               // 0x1D
    SLAVE_CMD_DONE,                     // 0x1E
    SLAVE_CMD_MODIFY_BAUD_RATE,

    SLAVE_CMD_MAX = 0x7F, //ACK state |= SLAVE_CMD_XXX in mw

} SLAVE_CMD;

typedef struct
{
    uint64_t chip_id;
    uint64_t uart_baudrate;
    uint64_t flash_id;
    uint64_t flash_size;
    uint64_t flash_bin_start_addr;
    uint64_t flash_bin_size;
    uint64_t flash_triple_addr;
    uint8_t  flash_clk_div;
    uint8_t  flash_sample_point;
    uint8_t  flash_clk_sel;
    uint8_t  flash_clk_calib;

    SLAVE_CMD en_slave_cmd_state;
    uint8_t   slave_uart_channel;
    //uint8_t   rx_buffer[BURN_UART_DATA_MAX];
} SLAVE_INFO;

typedef struct
{
    uint8_t  fw_num;
    uint32_t bin_length;
    uint32_t cur_read_offset;
} SLAVE_FW_INFO;

/**
 * @brief State machine operation type
 */
typedef enum
{
    SM_OP_NONE = 0,         // No operation
    SM_OP_PROGRAM,          // Programming operation
    SM_OP_CRC_CHECK,        // CRC check operation
} SM_OPERATION;

/**
 * @brief Unified state machine states (for concurrent programming and CRC check)
 */
typedef enum
{
    SM_STATE_IDLE = 0,          // Idle state, ready to start
    SM_STATE_READ_FLASH,        // Reading firmware from flash (program only)
    SM_STATE_PREPARE_CMD,       // Preparing UART command
    SM_STATE_TX_STARTING,       // Starting UART TX/RX DMA
    SM_STATE_WAIT_TX,           // Waiting for TX DMA complete
    SM_STATE_WAIT_RX,           // Waiting for RX DMA complete  
    SM_STATE_CHECK_ACK,         // Checking ACK response
    SM_STATE_VERIFY_CRC,        // Final CRC comparison (CRC only)
    SM_STATE_COMPLETE,          // Operation complete
    SM_STATE_ERROR,             // Error occurred
} SM_STATE;

// Keep old names for compatibility
typedef SM_STATE PROG_STATE;
typedef SM_STATE CRC_STATE;
#define PROG_STATE_IDLE         SM_STATE_IDLE
#define PROG_STATE_READ_FLASH   SM_STATE_READ_FLASH
#define PROG_STATE_PREPARE_CMD  SM_STATE_PREPARE_CMD
#define PROG_STATE_TX_STARTING  SM_STATE_TX_STARTING
#define PROG_STATE_WAIT_TX      SM_STATE_WAIT_TX
#define PROG_STATE_WAIT_RX      SM_STATE_WAIT_RX
#define PROG_STATE_CHECK_ACK    SM_STATE_CHECK_ACK
#define PROG_STATE_COMPLETE     SM_STATE_COMPLETE
#define PROG_STATE_ERROR        SM_STATE_ERROR
#define CRC_STATE_IDLE          SM_STATE_IDLE
#define CRC_STATE_PREPARE_CMD   SM_STATE_PREPARE_CMD
#define CRC_STATE_TX_STARTING   SM_STATE_TX_STARTING
#define CRC_STATE_WAIT_TX       SM_STATE_WAIT_TX
#define CRC_STATE_WAIT_RX       SM_STATE_WAIT_RX
#define CRC_STATE_CHECK_ACK     SM_STATE_CHECK_ACK
#define CRC_STATE_VERIFY_CRC    SM_STATE_VERIFY_CRC
#define CRC_STATE_COMPLETE      SM_STATE_COMPLETE
#define CRC_STATE_ERROR         SM_STATE_ERROR

void ftd_mw_slave_manager_start_ld(SLAVE_INFO* p_st_slave_info);
/////////////////// debug
bool ftd_mw_slave_manager_start_ld_test(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_modify_baud_rate(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_disable_wp(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_erase_test(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_program_test(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_program_sm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_program_sm_is_error(uint8_t channel);
PROG_STATE ftd_mw_slave_manager_program_sm_get_state(uint8_t channel);
bool ftd_mw_slave_manager_enable_wp(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_read_crc_test(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_read_crc_sm(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_read_crc_sm_is_error(uint8_t channel);
bool ftd_mw_slave_manager_read_crc_sm_get_result(uint8_t channel);
bool ftd_mw_slave_manager_disable_wp_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_erase_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_program_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_read_crc_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_sort(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
///////////////////////// debug end
void ftd_mw_slave_manager_set_default_slave_info(SLAVE_INFO* p_st_slave_info);

#endif 
