#ifndef __FTD_MW_SLAVE_MANAGER_H__
#define __FTD_MW_SLAVE_MANAGER_H__ 

#include "ftd_drv_burn_uart.h"
#include "ftd_mw_hc_manager.h"   // for debug 
#include "ftd_data_model.h"

#include <stdint.h>
#include <stdbool.h>

///////////////////// for deubg
#define FT_TEST_ROM

#define FT_TEST_SLAVE_ADDR (0x40000)
#define FT_TEST_SLAVE_BIN_SIZE (0x3D8C)
#define FT_TEST_SLAVE_BIN_ADDR (0x20000900)

#define FT_TEST_SLAVE_BIN_JUMP_ADDR     (0x20004218)

typedef enum
{
    SLAVE_EXT_CMD_ERASE_FLASH = 0x004F,
    SLAVE_EXT_CMD_READ_FLASH = 0x0050,
    SLAVE_EXT_CMD_PROG_FLASH = 0x0051,
} EN_SLAVE_EXT_CMD;


#define SLAVE_BOOT_TRIGGER_CNT              (3)
#define SLAVE_BOOT_TRIGGER_DELAY            (80000)//(1000) // 1ms

#define SLAVE_DISABLE_WP_TRIGGER_CNT        (1)

#define SLAVE_SEND_PACKET_DELAY_MS          (250)

//#define SLAVE_CMD_RETRY_CNT_MAX             (3)


#define SLAVE_FLASH_TEST_ADDR               (0x08021000)
#define SLAVE_FLASH_BIN_ADDR                (0x08008000)
#define SLAVE_FLASH_START_ADDR              SLAVE_FLASH_TEST_ADDR
#define SLAVE_FLASH_PAGE_SIZE               (0x00000100) // 256 bytes per page

// CHIP id 0 : FL100, MAP 0 : memmap version 0
// AUTHOR: authorization info, like rollcode, triple, motor encryption key, etc
// CLIENT: client info
// CONFIG_A, CONFIG_B: configuration data bin partition A and B, generated by automatic compile tool
// FW_BIN_A, FW_BIN_B: fw bin partition A and B
// DEBUG: for wirte debug, could P/E without quit WP operation
#define SLAVE_FLASH_CHIP_0_MAP_0_AUTHOR_ADDR            (0x08002000)
#define SLAVE_FLASH_CHIP_0_MAP_0_CLIENT_ADDR            (0x08003000)
#define SLAVE_FLASH_CHIP_0_MAP_0_CONFIG_A_ADDR          (0x08004000)
#define SLAVE_FLASH_CHIP_0_MAP_0_CONFIG_B_ADDR          (0x08005000)
#define SLAVE_FLASH_CHIP_0_MAP_0_FW_BIN_A_ADDR          (0x08008000)
#define SLAVE_FLASH_CHIP_0_MAP_0_FW_BIN_B_ADDR          (0x08020000)
#define SLAVE_FLASH_CHIP_0_MAP_0_DEBUG_ADDR             (0x08021000)
#define SLAVE_FLASH_CHIP_0_MAP_0_MAX_ADDR               (0x08040000)

/////////////////// CHIP FLASH ADDRESS MAP TABLE
// Chip family enumeration
typedef enum
{
    CHIP_FAMILY_FL100 = 0,     // A series chips (FM124AM, FM128AM, FL116AM, FL110AM)
    CHIP_FAMILY_FL100B = 1,     // B series chips (FM124BM, FM128BM, FL116BM, FL110BM)
    CHIP_FAMILY_PY32 = 2,      // C series chips (FM01011A)
    CHIP_FAMILY_CW32 = 3,      // D series chips (FM02021A)
    CHIP_FAMILY_MAX
} CHIP_FAMILY;

// Chip flash address map structure
typedef struct
{
    const char* chip_name;      // Chip name (e.g., "FM124AM")
    uint16_t    chip_code;      // Chip code (e.g., 0x2202)
    CHIP_FAMILY chip_family;    // Chip family (FL100/FL100B)
    // 2M/4M Flash addresses
    uint32_t    fw_bin_a_addr;  // FW partition A start address
    uint32_t    fw_bin_b_addr;  // FW partition B start address
    uint32_t    fw_size;        // FW partition size (bytes)
    // 1M Flash addresses (0 if not supported)
    uint32_t    fw_bin_a_addr_1m; // 1M Flash FW partition A start address
    uint32_t    fw_bin_b_addr_1m; // 1M Flash FW partition B start address
    uint32_t    fw_size_1m;       // 1M Flash FW partition size (bytes)
    // Config partition addresses
    uint32_t    config_a_addr;  // Config partition A address
    uint32_t    config_b_addr;  // Config partition B address
    uint32_t    config_size;    // Config partition size (bytes)
    // Authorization info addresses
    uint32_t    author_addr;    // Rollcode/PID/Triple address
    uint32_t    author_size;    // Authorization info size (bytes)
    uint32_t 	burn_info_addr; // Burn info address
    uint32_t    burn_info_size; // Burn info size (bytes)
} CHIP_FLASH_ADDR_MAP;

// Get chip flash map by chip code
const CHIP_FLASH_ADDR_MAP* ftd_mw_slave_get_chip_flash_map(uint16_t chip_code);
// Get chip flash map count
uint8_t ftd_mw_slave_get_chip_flash_map_count(void);
/////////////////// CHIP FLASH ADDRESS MAP TABLE END

#define SLAVE_FLASH_OP_ADDR_SIZE            (4)

/////////////////// SLAVE FLASH STATUS
#define SLAVE_FLASH_STATUS_LEN              (2)
#define SLAVE_FLASH_STATUS_ACK_LEN          (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_STATUS_LEN + CHECKSUM_SIZE)
/////////////////// SLAVE FLASH STATUS END

/////////////////// SLAVE FLASH ERASE
#define SLAVE_FLASH_ERASE_LEN               (4)
#define SLAVE_FLASH_ERASE_ACK_SIZE          (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_ERASE_LEN + CHECKSUM_SIZE)
/////////////////// SLAVE FLASH ERASE END

/////////////////// SLAVE FLASH PROG 
#define SLAVE_FLASH_PROG_SIZE               (SLAVE_FLASH_PAGE_SIZE << 1) // 2 pages, must be multiple of 1page
#define SLAVE_FLASH_OP_LENGTH_SIZE          (3)
#define SLAVE_FLASH_PROG_PRAM_LEN_OFFSET    (FRAME_HEADER_SIZE + CMD_SIZE)
#define SLAVE_FLASH_PROG_EXT_CMD_OFFSET     (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE)
#define SLAVE_FLASH_PROG_ADDR_OFFSET        (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE)
#define SLAVE_FLASH_PROG_LEN_OFFSET         (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE)
#define SLAVE_FLASH_PROG_DATA_OFFSET        (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_OP_LENGTH_SIZE)
#define SLAVE_FLASH_PROG_PRAM_LEN_MAX       (EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_OP_LENGTH_SIZE + SLAVE_FLASH_PROG_SIZE)
#define SLAVE_FLASH_PROG_CMD_SIZE_MAX       (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_OP_LENGTH_SIZE + SLAVE_FLASH_PROG_SIZE + CHECKSUM_SIZE)
#define SLAVE_FLASH_PROG_ACK_LEN            (0x0E)// fixed 14
/////////////////// SLAVE FLASH PROG END

/////////////////// SLAVE FLASH READ 
#define SLAVE_FLASH_READ_SIZE               (SLAVE_FLASH_PAGE_SIZE << 2) // 4 pages, must be multiple of 1page
#define SLAVE_FLASH_READ_LENGTH_SIZE        (4)
#define SLAVE_FLASH_READ_DATA_OFFSET        (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_READ_LENGTH_SIZE)
#define SLAVE_FLASH_READ_CMD_SIZE_MAX       (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_READ_LENGTH_SIZE + CHECKSUM_SIZE)
#define SLAVE_FLASH_READ_CMD_ACK_SIZE_MAX   (FRAME_HEADER_SIZE + CMD_SIZE + PARAM_LEN_SIZE + EXTEND_CMD_SIZE + SLAVE_FLASH_OP_ADDR_SIZE + SLAVE_FLASH_READ_LENGTH_SIZE + SLAVE_FLASH_READ_SIZE + CHECKSUM_SIZE)
/////////////////// SLAVE FLASH READ END


#define AUTHOR_INFO_CRC_LEN                 (2)
#define BURN_INFO_CRC_LEN                   (2)



//////////////////////////// debug end
typedef enum
{
    SLAVE_CMD_NONE,                         // 0x00
    SLAVE_CMD_ENTER_BOOT_LOADER,            // 0x01
    SLAVE_CMD_CHECK_CURRENT_VOLTAGE,        // 0x02
    SLAVE_CMD_READ_CHIP_ID,                 // 0x03
    SLAVE_CMD_REBOOT_CHIP,                  // 0x04
    SLAVE_CMD_SET_CPU_CLK,                  // 0x05
    SLAVE_CMD_SET_UART_BAUDRATE,            // 0x06
    SLAVE_CMD_MODIFY_BAUD_RATE,             // 0x07

    SLAVE_CMD_READ_PRODUCTION_TEST_STATUS,  // 0x08
    SLAVE_CMD_SET_PROGRAM_JUMP,             // 0x09
    SLAVE_CMD_WAIT_CALIBRATION,
    SLAVE_CMD_READ_CODE_CRC,                // 0x0A

    SLAVE_CMD_READ_FLASH_ID,                // 0x0B
    SLAVE_CMD_READ_FLASH_STATUS_REG,        // 0x0C
    SLAVE_CMD_SET_FLASH_STATUS_REG,         // 0x0D
    SLAVE_CMD_SET_FLASH_STATUS_QUIT_WP,     // 0x0E
    SLAVE_CMD_SET_FLASH_READ_MODE,          // 0x0F
    SLAVE_CMD_SET_FLASH_WRITE_MODE,         // 0x10
    SLAVE_CMD_SET_FLASH_CLK_DIV,            // 0x11
    SLAVE_CMD_SET_FLASH_SAMPLE_POINT,       // 0x12
    SLAVE_CMD_ERASE_ENTIRE_FLASH,           // 0x13
    SLAVE_CMD_ERASE_FLASH_SECTOR,           // 0x14
    SLAVE_CMD_READ_FLASH_OR_RAM_DATA,       // 0x15
    SLAVE_CMD_WRITE_FLASH_DATA,             // 0x16
    SLAVE_CMD_WRITE_RAM_DATA,               // 0x17
    SLAVE_CMD_RESET_FLASH,                  // 0x18
    SLAVE_CMD_SET_FLASH_STATUS_QUIT_WP_PARM,// 0x19
    SLAVE_CMD_ERASE_FLASH_SECTOR_PARM,      // 0x1A
    SLAVE_CMD_WRITE_FLASH_DATA_PARM,        // 0x1B
    SLAVE_CMD_SET_FLASH_STATUS_REG_PARM,    // 0x1C
    SLAVE_CMD_READ_CODE_CRC_PARM,           // 0x1D

    SLAVE_CMD_STATE_SORT,                   // 0x1E
    SLAVE_CMD_DONE,                         // 0x1F

    SLAVE_CMD_FT_TEST,
    SLAVE_CMD_FT_MODIFY_BAUD_RATE,
    SLAVE_CMD_FT_ENTER_BOOT_LOADER,
    SLAVE_CMD_FT_WRITE_CHIP_ID,
    SLAVE_CMD_FT_SET_FLASH_STATUS_QUIT_WP,
    SLAVE_CMD_FT_ERASE_FLASH_SECTOR,
    SLAVE_CMD_FT_WRITE_FLASH_DATA,
    SLAVE_CMD_FT_SET_FLASH_STATUS_REG,
    SLAVE_CMD_FT_RESTATE,

    SLAVE_CMD_SEND_PACKET_ADDR,
    SLAVE_CMD_JUMP_BOOTLOADER,
    SLAVE_CMD_TEST_CURRENT_AT_0DB,          // 0x20
    SLAVE_CMD_TEST_CURRENT_AT_5DB,          // 0x21
    SLAVE_CMD_TEST_CURRENT_AT_STATIC,       // 0x22
    SLAVE_CMD_TEST_RECEIVE_SENSITIVITY,     // 0x23
    SLAVE_CMD_TEST_RECEIVE_SENSITIVITY_VALUE,// 0x24
    SLAVE_CMD_CALIBRATE_MADC,               // 0x25
    SLAVE_CMD_CALIBRATE_MADC_VALUE,         // 0x26
    SLAVE_CMD_CALIBRATE_GPADC,              // 0x27
    SLAVE_CMD_CALIBRATE_GPADC_VALUE,        // 0x28
    SLAVE_CMD_CALIBRATE_CLOCK,              // 0x29
    SLAVE_CMD_CALIBRATE_CLOCK_VALUE,        // 0x2A
    SLAVE_CMD_TEST_SLEEP_CURRENT,           // 0x2B


    SLAVE_CMD_MAX = 0x7F,                   // ACK state |= SLAVE_CMD_XXX in mw

} SLAVE_CMD;

typedef struct
{
    uint64_t chip_id;
    uint64_t uart_baudrate;
    uint64_t flash_id;
    uint64_t flash_size;
    uint64_t flash_bin_start_addr;
    uint64_t flash_bin_size;
    uint64_t flash_triple_addr;
    uint8_t  flash_clk_div;
    uint8_t  flash_sample_point;
    uint8_t  flash_clk_sel;
    uint8_t  flash_clk_calib;

    SLAVE_CMD en_slave_cmd_state;
    uint8_t   slave_uart_channel;
    //uint8_t   rx_buffer[BURN_UART_DATA_MAX];
} SLAVE_INFO;

typedef struct
{
    uint8_t  fw_num;
    uint32_t bin_length;
    uint32_t cur_read_offset;
} SLAVE_FW_INFO;

/**
 * @brief State machine operation type
 */
typedef enum
{
    SM_OP_NONE = 0,         // No operation
    SM_OP_BOOT_TRIGGER,     // Bootloader trigger operation
    SM_OP_PROGRAM,          // Programming operation
    SM_OP_RAM_PROGRAM,      // RAM programming operation
    SM_OP_CRC_CHECK,        // CRC check operation
    SM_OP_CALIB_TEST,       // Calibration/Test operation
} SM_OPERATION;

/**
 * @brief Calibration/Test type enumeration
 */
typedef enum
{
    CALIB_TYPE_NONE = 0,        // No calibration
    CALIB_TYPE_GPADC,           // GPADC calibration
    CALIB_TYPE_CLOCK,           // Clock calibration
    CALIB_TYPE_MADC,            // MADC calibration
    TEST_TYPE_SLEEP_CURRENT,    // Sleep current test
    TEST_TYPE_STATIC_CURRENT,   // Static current test
} CALIB_TEST_TYPE;

/**
 * @brief Unified state machine states (for concurrent programming and CRC check)
 */
typedef enum
{
    SM_STATE_IDLE = 0,          // Idle state, ready to start

    // Boot trigger specific states
    SM_STATE_POWER_OFF,         // Power off slave (boot only)
    SM_STATE_WAIT_POWER_OFF,    // Waiting for power off stable (boot only)
    SM_STATE_POWER_ON,          // Power on slave (boot only)
    SM_STATE_WAIT_POWER_STABLE, // Waiting for power stable (boot only)
    SM_STATE_RX_START,          // Start UART RX (boot only)
    SM_STATE_TX_CMD,            // Send trigger command (boot only)
    SM_STATE_EXTENDED_WAIT,     // Extended wait for response (boot only)

    // Program/CRC common states
    SM_STATE_READ_FLASH,        // Reading firmware from flash (program only)
    SM_STATE_PREPARE_CMD,       // Preparing UART command
    SM_STATE_TX_STARTING,       // Starting UART TX/RX DMA
    SM_STATE_WAIT_TX,           // Waiting for TX DMA complete
    SM_STATE_WAIT_RX,           // Waiting for RX DMA complete  
    SM_STATE_CHECK_ACK,         // Checking ACK response
    SM_STATE_VERIFY_CRC,        // Final CRC comparison (CRC only)

    // Calibration/Test specific states
    SM_STATE_WAIT_VALUE,        // Waiting for calibration value response
    SM_STATE_PARSE_VALUE,       // Parsing calibration value
    SM_STATE_MEASURE_CURRENT,   // Measuring current (sleep/static)
    SM_STATE_CALIBRATE_VALUE,   // Calibrating value (placeholder)


    // Terminal states
    SM_STATE_COMPLETE,          // Operation complete
    SM_STATE_ERROR,             // Error occurred
} SM_STATE;

// Keep old names for compatibility
typedef SM_STATE PROG_STATE;
typedef SM_STATE CRC_STATE;
#define PROG_STATE_IDLE         SM_STATE_IDLE
#define PROG_STATE_READ_FLASH   SM_STATE_READ_FLASH
#define PROG_STATE_PREPARE_CMD  SM_STATE_PREPARE_CMD
#define PROG_STATE_TX_STARTING  SM_STATE_TX_STARTING
#define PROG_STATE_WAIT_TX      SM_STATE_WAIT_TX
#define PROG_STATE_WAIT_RX      SM_STATE_WAIT_RX
#define PROG_STATE_CHECK_ACK    SM_STATE_CHECK_ACK
#define PROG_STATE_COMPLETE     SM_STATE_COMPLETE
#define PROG_STATE_ERROR        SM_STATE_ERROR
#define CRC_STATE_IDLE          SM_STATE_IDLE
#define CRC_STATE_PREPARE_CMD   SM_STATE_PREPARE_CMD
#define CRC_STATE_TX_STARTING   SM_STATE_TX_STARTING
#define CRC_STATE_WAIT_TX       SM_STATE_WAIT_TX
#define CRC_STATE_WAIT_RX       SM_STATE_WAIT_RX
#define CRC_STATE_CHECK_ACK     SM_STATE_CHECK_ACK
#define CRC_STATE_VERIFY_CRC    SM_STATE_VERIFY_CRC
#define CRC_STATE_COMPLETE      SM_STATE_COMPLETE
#define CRC_STATE_ERROR         SM_STATE_ERROR

// Bootloader state machine compatibility macros
typedef SM_STATE BOOT_SM_STATE;
#define BOOT_SM_STATE_IDLE              SM_STATE_IDLE
#define BOOT_SM_STATE_POWER_OFF         SM_STATE_POWER_OFF
#define BOOT_SM_STATE_WAIT_POWER_OFF    SM_STATE_WAIT_POWER_OFF
#define BOOT_SM_STATE_POWER_ON          SM_STATE_POWER_ON
#define BOOT_SM_STATE_WAIT_POWER_STABLE SM_STATE_WAIT_POWER_STABLE
#define BOOT_SM_STATE_RX_START          SM_STATE_RX_START
#define BOOT_SM_STATE_TX_CMD            SM_STATE_TX_CMD
#define BOOT_SM_STATE_WAIT_RX           SM_STATE_WAIT_RX
#define BOOT_SM_STATE_CHECK_ACK         SM_STATE_CHECK_ACK
#define BOOT_SM_STATE_EXTENDED_WAIT     SM_STATE_EXTENDED_WAIT
#define BOOT_SM_STATE_COMPLETE          SM_STATE_COMPLETE
#define BOOT_SM_STATE_ERROR             SM_STATE_ERROR

// RAM Program state machine compatibility macros
typedef SM_STATE RAM_SM_STATE;
#define RAM_SM_STATE_IDLE         SM_STATE_IDLE
#define RAM_SM_STATE_READ_FLASH   SM_STATE_READ_FLASH
#define RAM_SM_STATE_PREPARE_CMD  SM_STATE_PREPARE_CMD
#define RAM_SM_STATE_TX_STARTING  SM_STATE_TX_STARTING
#define RAM_SM_STATE_WAIT_TX      SM_STATE_WAIT_TX
#define RAM_SM_STATE_WAIT_RX      SM_STATE_WAIT_RX
#define RAM_SM_STATE_CHECK_ACK    SM_STATE_CHECK_ACK
#define RAM_SM_STATE_COMPLETE     SM_STATE_COMPLETE
#define RAM_SM_STATE_ERROR        SM_STATE_ERROR

// Jump state machine compatibility macros
typedef SM_STATE JUMP_SM_STATE;
#define JUMP_SM_STATE_IDLE              SM_STATE_IDLE
#define JUMP_SM_STATE_PREPARE_CMD       SM_STATE_PREPARE_CMD
#define JUMP_SM_STATE_TX_STARTING       SM_STATE_TX_STARTING
#define JUMP_SM_STATE_WAIT_TX           SM_STATE_WAIT_TX
#define JUMP_SM_STATE_WAIT_RX           SM_STATE_WAIT_RX
#define JUMP_SM_STATE_CHECK_ACK         SM_STATE_CHECK_ACK
#define JUMP_SM_STATE_WAIT_CALIBRATION  SM_STATE_EXTENDED_WAIT
#define JUMP_SM_STATE_COMPLETE          SM_STATE_COMPLETE
#define JUMP_SM_STATE_ERROR             SM_STATE_ERROR

typedef SM_STATE FT_STATE;


void ftd_mw_slave_manager_start_ld(SLAVE_INFO* p_st_slave_info);
/////////////////// debug
bool ftd_mw_slave_manager_start_ld_test(SLAVE_INFO* p_st_slave_info);
// Bootloader state machine functions
bool ftd_mw_slave_manager_start_ld_sm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* p_burn_status);
bool ftd_mw_slave_manager_start_ld_sm_is_error(uint8_t channel);
bool ftd_mw_slave_manager_start_ld_sm_is_complete(uint8_t channel);
BOOT_SM_STATE ftd_mw_slave_manager_start_ld_sm_get_state(uint8_t channel);
void ftd_mw_slave_manager_start_ld_sm_reset(uint8_t channel);
bool ftd_mw_slave_manager_modify_baud_rate(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_disable_wp(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_erase_test(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_program_test(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_program_sm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_program_sm_is_error(uint8_t channel);
PROG_STATE ftd_mw_slave_manager_program_sm_get_state(uint8_t channel);

// Flash test state machine functions
bool ftd_mw_slave_ft_test_manager_program_test_sm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_ft_test_manager_program_test_sm_is_error(uint8_t channel);
RAM_SM_STATE ftd_mw_slave_ft_test_manager_program_test_sm_get_state(uint8_t channel);

// Jump state machine functions
bool ftd_mw_slave_manager_program_jump_sm(SLAVE_INFO* p_st_slave_info, uint32_t jump_addr);
bool ftd_mw_slave_manager_program_jump_sm_is_error(uint8_t channel);
JUMP_SM_STATE ftd_mw_slave_manager_program_jump_sm_get_state(uint8_t channel);

bool ftd_mw_slave_manager_enable_wp(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_read_crc_test(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_read_crc_sm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* p_burn_status);
bool ftd_mw_slave_manager_read_crc_sm_is_error(uint8_t channel);
bool ftd_mw_slave_manager_read_crc_sm_get_result(uint8_t channel);
bool ftd_mw_slave_manager_disable_wp_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_erase_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_program_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_read_crc_parm(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_sort(SLAVE_INFO* p_st_slave_info);

// Test current functions
bool ftd_mw_slave_manager_write_chip_id(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_test_send_packet_address(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_test_jump_bootloader(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_program_jump(SLAVE_INFO* p_st_slave_info, uint32_t jump_addr);
bool ftd_mw_slave_ft_test_manager_program_test(SLAVE_INFO* p_st_slave_info, CHANNEL_BURN_STATUS* st_channel_burn_status);
bool ftd_mw_slave_manager_test_current_at_0db(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_test_current_at_5db(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_test_current_at_static(SLAVE_INFO* p_st_slave_info);

// Calibration/Test functions (refactored to use unified state machine)
bool ftd_mw_slave_manager_calibrate_madc(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_calibrate_gpadc(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_calibrate_clock(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_test_sleep_current(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_test_current_at_static(SLAVE_INFO* p_st_slave_info);

// Calibration/Test state machine error check
bool ftd_mw_slave_manager_calib_test_is_error(uint8_t channel);

// Test state machine functions
bool ftd_mw_slave_manager_test_current_at_static_sm(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_calibrate_madc_sm(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_calibrate_gpadc_sm(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_calibrate_clock_sm(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_test_sleep_current_sm(SLAVE_INFO* p_st_slave_info);

// Test state machine error check
bool ftd_mw_slave_manager_test_sm_is_error(uint8_t channel);

// Test receiving sensitivity function
bool ftd_mw_slave_manager_test_receiving_sensitivity(SLAVE_INFO* p_st_slave_info);

// Calibration functions
bool ftd_mw_slave_manager_calibrate_madc(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_calibrate_gpadc(SLAVE_INFO* p_st_slave_info);
bool ftd_mw_slave_manager_calibrate_clock(SLAVE_INFO* p_st_slave_info);


bool ftd_mw_slave_manager_restart_test(SLAVE_INFO* p_st_slave_info);
///////////////////////// debug end
void ftd_mw_slave_manager_set_default_slave_info(SLAVE_INFO* p_st_slave_info);

#endif 
